services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - VF_REGION=vn
      - NODE_ENV=production
    networks:
      - vfdashboard-net

  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
      # Point to backend service name in internal network
      - PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - vfdashboard-net

networks:
  vfdashboard-net:
    driver: bridge
